name: Manage application

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The application environment name
        required: false
        default: test  

jobs:
  manage-core-infrastructure:
    name: Manage core infrastructure resources
    uses: keeonline/github-workflows/.github/workflows/reusable-core.yml@v0.0.3
    with:
      action: apply
      environment: ${{vars.INFRA_ENVIRONMENT}}
      iac_ref: v0.0.17
    secrets: inherit
    permissions:
      contents: write
      id-token: write


