name: Manage application related resources

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The application environment name
        required: false
        default: test  

jobs:
  manage-core-infrastructure:
    name: Manage core infrastructure resources
    uses: keeonline/infra-01-aws/.github/workflows/reusable-core.yml@v0.0.16
    with:
      action: apply
      environment: ${{vars.INFRA_ENVIRONMENT}}
      iac_version: v0.0.16
    secrets: inherit
    permissions:
      contents: write
      id-token: write


