name: Manage application

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The application environment name
        required: false
        default: test  
      
jobs:
  manage-application:
    name: Manage infratstructure (apply)
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    env:
      TF_VAR_app_environment: ${{inputs.environment}}
      TF_VAR_app_version: ${{github.ref_name}}
      TF_VAR_infra_environment: test
      TF_VAR_infra_version: dev
    permissions:
      contents: write
      id-token: write
    steps:
      
      - name: Provision cloud infrastructure
        uses: keeonline/github-actions/show@main
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          action: apply
          repo_name: infra-01-aws
          repo_ref: dev
          terraform_codedir: terraform/core
          environment: test
      
      - name: Deploy application
        uses: keeonline/github-actions/show@main
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          action: apply
          terraform_codedir: deploy/aws
          environment: test
          
      - name: Undeploy application
        uses: keeonline/github-actions/show@main
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          action: destroy
          terraform_codedir: deploy/aws
          environment: test
            
      - name: Destroy cloud infrastructure
        uses: keeonline/github-actions/show@main
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          action: destroy
          repo_name: infra-01-aws
          repo_ref: dev
          terraform_codedir: terraform/core
          environment: test
  
  