name: Manage application related resources

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Terraform action
        required: true
        options:
          - apply-plan
          - apply
          - destroy-plan
          - destroy
        default: apply-plan
      environment:
        type: environment
        description: The application environment name
        required: false
        default: test
      infra_environment:
        type: string
        description: The infrastructure environment into which the app will be deployed
        required: true
        default: test
  

jobs:
  execute:
    name: Manage resources ${{inputs.action}}
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    env:
      TF_VAR_infra_environment: ${{inputs.infra_environment}}
      TF_VAR_app_environment: ${{inputs.environment}}
      TF_VAR_iac_version: ${{github.ref_name}}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Clone the repository
        uses: actions/checkout/@v4
        with:
          fetch-depth: 0

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials/@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/IaC
          aws-region: ${{secrets.AWS_REGION}}

      - name: Install Terraform on runner
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform init
        run: | 
          terraform init \
            -backend-config="bucket=tf-state-bucket-${{secrets.AWS_ACCOUNT_ID}}" \
            -backend-config="key=${{github.event.repository.name}}.tfstate" \
            -backend-config="region=${{secrets.AWS_REGION}}" \
            -backend-config="dynamodb_table=terraform-lock" \

      - name: Conditionally set the planning mode to destroy
        id: planmode
        if: ${{contains(inputs.action,'destroy')}}
        run: echo "value=-destroy" >> $GITHUB_OUTPUT

      - name: Terraform plan
        run: | 
          terraform plan -input=false ${{steps.planmode.outputs.value}}
      - name: Terraform state change

        if: ${{!endsWith(inputs.action,'-plan')}}
        run: | 
          terraform apply -auto-approve -input=false ${{steps.planmode.outputs.value}}
      