name: Manage application

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The application environment name
        required: false
        default: test  
      
jobs:
  manage-infrastructure:
    name: Manage infratstructure (apply)
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    env:
      TF_VAR_environment: ${{inputs.environment}}
      TF_VAR_iac_version: ${{github.ref_name}}
      TF_VAR_infra_envrionment: dev
    permissions:
      contents: write
      id-token: write
    steps:
      - name: terraform apply infrastructure IaC
        uses: keeonline/github-actions/show@main
        with:
          aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
          aws_region: ${{secrets.AWS_REGION}}
          action: apply
          repo_name: infra-01-aws
          terraform_codedir: terraform/core
          environment: dev

