name: Push to feature branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
    feature-push:
        name: Build snapshot version
        runs-on: ubuntu-24.04
        steps:
            - name: Get the artifact version
              id: versions
              uses: keeonline/gh-actions/actions/artifact-version@v0.0.3

            - name: Build the application
              uses: keeonline/gh-actions/actions/java-build@v0.0.3
              with:
                artifact_version: ${{steps.versions.outputs.branch}}

            - name: Package the application as an image
              uses: keeonline/gh-actions/actions/docker-build@v0.0.3
              with:
                image: chameleon
                artifact_version: ${{steps.versions.outputs.branch}}
            
            - name: Setup docker compose
              uses: keeonline/gh-actions/actions/setup-docker-compose@v0.0.3
              with:
                version: 2.39.1

            - name: Start the chameleon service
              working-directory: servicetest/karate
              run: |
                echo "VERSION=${{steps.versions.outputs.branch}}" >> .env
                cat .env
                docker-compose up -d
                sleep 5

            - name: Execute the service tests
              uses: keeonline/reference-github-actions/actions/karate-tests@l2
              with:
                tests_directory: servicetest/karate
                reports_upload_title: Service Test Reports

            - name: Stop the chameleon service
              if: always()
              working-directory: servicetest/karate
              run: |
                docker-compose down

            - name: Publish the image
              uses: keeonline/gh-actions/actions/dockerhub-publish@v0.0.3
              with:
                username: ${{vars.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}
                source_image: chameleon:${{steps.versions.outputs.branch}}
                target_image: ${{vars.DOCKERHUB_USERNAME}}/chameleon:${{steps.versions.outputs.branch}}