name: Push on Feature Branch

on: 
    push:
        branches:
            - '**'
            - '!main'

jobs:
    feature-push:
      name: Build snapshot version
      uses: keeonline/reference-gh-workflows/.github/workflows/app-on-push-feature.yml@app-on-push
      permissions:
        id-token: write
      secrets:
        inherit
