name: Run the System Integration Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The GitHub environment
        required: false
        default: test
      iac-ref:
        type: string
        description: The reference (tag or branch e.g., 'v0.0.1' or 'feature-123') of the IaC codebase
        required: false
        default: main

jobs:
  execute:
    name: Run the SITs
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout IaC repo
        uses: actions/checkout@v4
        with:
          repository: keeonline/infra-01-aws
          ref: ${{inputs.iac-ref}}
          path: iac

      - name: list IaC files
        run: |
          ls -lsa iac

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials/@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/IaC
          aws-region: ${{secrets.AWS_REGION}}

      - name: Install Terraform on runner
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform init
        working-directory: sit
        run: | 
          terraform init \
            -backend-config="bucket=tf-state-bucket-${{secrets.AWS_ACCOUNT_ID}}" \
            -backend-config="key=${{inputs.environment}}-${{github.event.repository.name}}.tfstate" \
            -backend-config="region=${{secrets.AWS_REGION}}" \
            -backend-config="dynamodb_table=terraform-lock"

      - name: Provision platform infrastructure
        working-directory: sit
        run: | 
          terraform apply -auto-approve -input=false

      # # This should trigger a 'repository_dispatch' to execute the IaC with a given sha and set of args ???

      # # add processing to build local image and run intergration tests using docker compose

      # - uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '23'

      # - name: Download the standalone karate jar
      #   run: |
      #     wget -O /opt/karate.jar https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar

      # - name: Execute the SITs using karate
      #   working-directory: sit/karate
      #   run: |
      #     java -jar /opt/karate.jar -h

      - name: Destroy platform infrastructure
        working-directory: sit
        run: | 
          terraform destroy -auto-approve -input=false

