name: Run the System Integration Tests in a ephemeral environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: false
        default: test  
      
jobs:
  get-infra-env:
    name: Get environment
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    outputs:
      infra_env: ${{ steps.infra_env.outputs.value }}
    steps:
      - id: infra_env
        run: echo "value=${{vars.INFRA_ENVIRONMENT}}" >> $GITHUB_OUTPUT

  provision-infra:
    name: Manage resources
    needs: get-infra-env
    uses: keeonline/reference-infra-aws/.github/workflows/reusable-manage-infra.yml@bob
    permissions:
      id-token: write
    secrets:
      inherit
    with:
      action: apply-plan
      environment: ${{needs.get-infra-env.outputs.infra_env}}
      repo_name: keeonline/reference-infra-aws
      repo_ref: v0.0.56

