name: Run the System Integration Tests in a ephemeral environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: false
        default: test  

jobs:
  infra-config:
    name: Get infra configuration
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    outputs:
      environment: ${{ steps.get_config.outputs.environment }}
      repo_name: ${{ steps.get_config.outputs.repo_name }}
      repo_ref: ${{ steps.get_config.outputs.repo_ref }}
    steps:
      - id: get_config
        run: |
          echo "environment=${{vars.INFRA_ENVIRONMENT}}" >> $GITHUB_OUTPUT
          echo "repo_name=keeonline/reference-infra-aws" >> $GITHUB_OUTPUT
          echo "repo_ref=v0.0.56" >> $GITHUB_OUTPUT

  provision-infra:
    name: Provision infrastructure
    needs: infra-config
    uses: keeonline/reference-infra-aws/.github/workflows/reusable-manage-infra.yml@bob
    permissions:
      id-token: write
    secrets:
      inherit
    with:
      action: apply-plan
      environment: ${{needs.infra-config.outputs.environment}}
      repo_name: ${{needs.infra-config.outputs.repo_name}}
      repo_ref: ${{needs.infra-config.outputs.repo_ref}}

  teardown-infra:
    name: Teardown infrastructure
    needs: provision-infra
    uses: keeonline/reference-infra-aws/.github/workflows/reusable-manage-infra.yml@bob
    permissions:
      id-token: write
    secrets:
      inherit
    with:
      action: destroy-plan
      environment: ${{needs.infra-config.outputs.environment}}
      repo_name: ${{needs.infra-config.outputs.repo_name}}
      repo_ref: ${{needs.infra-config.outputs.repo_ref}}
