name: Run the System Integration Tests in a ephemeral environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: false
        default: test  

env:
  INFRA_REPO_NAME: keeonline/reference-infra-aws
  INFRA_REPO_REF: v0.0.56
      
jobs:
  get-infra-env:
    name: Get infra environment
    runs-on: ubuntu-24.04
    environment: ${{inputs.environment}}
    outputs:
      infra_env: ${{ steps.infra_env.outputs.value }}
    steps:
      - id: infra_env
        run: echo "value=${{vars.INFRA_ENVIRONMENT}}" >> $GITHUB_OUTPUT

  provision-infra:
    name: Provision infrastructure
    needs: get-infra-env
    uses: keeonline/reference-infra-aws/.github/workflows/reusable-manage-infra.yml@bob
    permissions:
      id-token: write
    secrets:
      inherit
    with:
      action: apply-plan
      environment: ${{needs.get-infra-env.outputs.infra_env}}
      repo_name: $INFRA_REPO_NAME
      repo_ref: $INFRA_REPO_REF

  teardown-infra:
    name: Teardown infrastructure
    needs: provision-infra
    uses: keeonline/reference-infra-aws/.github/workflows/reusable-manage-infra.yml@bob
    permissions:
      id-token: write
    secrets:
      inherit
    with:
      action: destroy-plan
      environment: ${{needs.get-infra-env.outputs.infra_env}}
      repo_name: $INFRA_REPO_NAME
      repo_ref: $INFRA_REPO_REF

